#!/usr/bin/env bash

TEST_TYPE=${1:-e2e}

function run_test() {
  local template=$1

  echo -e "\n***** $TEST_TYPE for $template *****\n"

  TEMPLATE=$template npm run "$TEST_TYPE" e2e/example.spec.ts
}

STARTERS=angular-example,astro-example,nextjs-example,react-example,react-ts-example,sveltekit-example,vue-example

for template in $(echo $STARTERS | sed "s/,/ /g"); do
  run_test "$template"
done