name: Setup E2EEnvironment

description: Installs the Juno CLI and caches Docker layers

runs:
  using: 'composite'
  steps:
    - name: Install Juno CLI
      run: npm i -g @junobuild/cli
      shell: bash

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /home/runner/.docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-
