name: E2E Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Setup E2E Environment
        uses: ./.github/actions/setup-e2e-env

      - name: Install Templates Dependencies
        run: ./scripts/install-deps

      - name: Run tests
        run: |
          juno dev start --headless

  may-merge:
    needs: ['e2e']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
