name: E2E Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Setup E2E Environment
        uses: ./.github/actions/setup-e2e-env

      - name: Install Templates Dependencies
        run: ./scripts/install-deps

      - name: Run emulator
        run: |
          set -e
          juno dev start --headless &
          juno dev wait
          juno login --emulator --mode development
          juno config --mode development

      - name: Run tests
        run: ./scripts/e2e e2e:ci

      - name: Upload Playwright report on failure
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3

      - name: Upload Playwright results on failure
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results
          path: test-results/
          retention-days: 3

  may-merge:
    needs: ['e2e']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
