name: Update boilerplate

on:
  schedule:
    - cron: '30 3 * * MON'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Install Juno CLI
        run: npm i -g @junobuild/cli
        shell: bash

      - name: Update
        run: npm run copy:boilerplate

      - name: Check for Changes
        run: |
          if ! git diff --quiet; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          fi

      # This action creates a PR only if there are changes.
      - name: Create Pull Request
        if: env.CHANGES_DETECTED == 'true'
        uses: ./.github/actions/create-pr
        with:
          branch: bot-cli-docs-update
          title: 'feat: Update boilerplate'
          body: |
            Modifications have been made to the templates of the CLI.
